# -*- coding: utf-8 -*-
"""cleaning_script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17DXiWZ7Wg4R7F2tgasK5gtE-g7ezHUIN
"""

import pandas as pd
import numpy as np

import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "TMDB_movie_dataset_v11.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "asaniczka/tmdb-movies-dataset-2023-930k-movies",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df.head())

# =========================================================
# INITIAL INSPECTION
# =========================================================

print("Initial shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

# =========================================================
# STEP 1: DROP USELESS / HIGHLY SPARSE COLUMNS
# =========================================================

columns_to_drop = [
    'backdrop_path',
    'homepage',
    'poster_path'
]

df = df.drop(
    columns=[col for col in columns_to_drop if col in df.columns]
)

# =========================================================
# STEP 2: RENAME PRIMARY KEY
# =========================================================

df = df.rename(columns={'id': 'movie_id'})

# =========================================================
# STEP 3: REMOVE DUPLICATES
# =========================================================

before = df.shape[0]

df = df.drop_duplicates(subset='movie_id')

after = df.shape[0]

print(f"\nRemoved {before - after} duplicate rows")

# =========================================================
# STEP 4: CLEAN NUMERIC COLUMNS
# =========================================================

numeric_columns = [
    'budget',
    'revenue',
    'runtime',
    'vote_average',
    'vote_count',
    'popularity'
]

for col in numeric_columns:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# =========================================================
# STEP 5: REPLACE INVALID ZEROS WITH NaN
# =========================================================

# Budget/revenue of 0 usually means "unknown"
df['budget'] = df['budget'].replace(0, np.nan)
df['revenue'] = df['revenue'].replace(0, np.nan)

# Runtime of 0 is invalid
df['runtime'] = df['runtime'].replace(0, np.nan)

# =========================================================
# STEP 6: REMOVE EXTREME / INVALID VALUES
# =========================================================

# Remove absurd runtimes
df = df[
    df['runtime'].isna() |
    ((df['runtime'] >= 1) & (df['runtime'] <= 600))
]

# Ratings should be between 0 and 10
df = df[
    df['vote_average'].isna() |
    ((df['vote_average'] >= 0) &
     (df['vote_average'] <= 10))
]

# Vote counts should not be negative
df = df[
    df['vote_count'].isna() |
    (df['vote_count'] >= 0)
]

# =========================================================
# STEP 7: CLEAN BOOLEAN COLUMN
# =========================================================

df['adult'] = df['adult'].map({
    True: 1,
    False: 0,
    'True': 1,
    'False': 0
})

# =========================================================
# STEP 8: CLEAN TEXT COLUMNS
# =========================================================

text_columns = [
    'title',
    'original_title',
    'overview',
    'tagline',
    'status'
]

for col in text_columns:
    if col in df.columns:
        df[col] = df[col].astype(str).str.strip()

# Clean status formatting
df['status'] = df['status'].str.title()

# =========================================================
# STEP 9: CLEAN DATES
# =========================================================

df['release_date'] = pd.to_datetime(
    df['release_date'],
    errors='coerce'
)

# Feature engineering
df['release_year'] = df['release_date'].dt.year

# =========================================================
# STEP 10: HANDLE MISSING TITLES
# =========================================================

df = df.dropna(subset=['title'])

# =========================================================
# STEP 11: FINAL NULL SUMMARY
# =========================================================

null_summary = pd.DataFrame({
    'null_count': df.isnull().sum(),
    'null_percent': (
        df.isnull().sum() / len(df)
    ) * 100
})

null_summary = null_summary.sort_values(
    by='null_count',
    ascending=False
)

print("\nNull Summary:")
print(null_summary)

# =========================================================
# STEP 12: FINAL DATASET SUMMARY
# =========================================================

print("\nFinal shape:", df.shape)

print("\nData types:")
print(df.dtypes)

print("\nPreview:")
print(df.head(3))

final_df = df[df['revenue'].notna()]
print(final_df.shape)

final_df.to_csv("TMDB_cleaned_revenue.csv")